### ISSUE TITLE
About how to cal the distance between the tag and camera.

### ISSUE THREAD

**Issue by BlackJocker1995** [christianrauch/apriltag2#1]
At first, i appreciate you sincerely.just i have some question about apritag than how dose it calcuate the distance between the tag and camera.The demo do not release.

**Comment by christianrauch** [comment]
This is just a CMake wrapper for the original apriltag2 library from https://april.eecs.umich.edu/software/apriltag.html which provides the 2D corner coordinates and the homography of the markers. To get the full pose of the marker in the camera frame, you need to know the intrinsic parameters of the camera and the physical size of the marker edge.

I am using the library in a ROS2 node: https://github.com/christianrauch/apriltag2_node. The method `AprilTag2Node::getPose(const matd_t& H, geometry_msgs::msg::Transform& t)` computes the pose of the marker given the homography matrix H that you get from `apriltag_detection_t` after detection. The implementation is based on: https://dsp.stackexchange.com/a/2737/31703.

**Comment by BlackJocker1995** [comment]
thank you for your response
